/**
 * @description       : 
 * @author            : Leandro Palma
 * @group             : 
 * @last modified on  : 17/08/2020
 * @last modified by  : Leandro Palma
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   17/08/2020   Leandro Palma   Initial Version
**/
public with sharing class TreinamentoHelper {
    public string name ='Branch Dev';
    
    public TreinamentoHelper() {

    }
}
